; Moodle PHP runtime settings
memory_limit = 512M
max_input_vars = 5000
post_max_size = 2G
upload_max_filesize = 2G
max_execution_time = 300
max_input_time = 600
default_charset = "UTF-8"
date.timezone = America/Sao_Paulo
